### PR TITLE
X011 include banned users in seed

### PR DESCRIPTION
**Pull request by kieranw-8**

### CODE REVIEW

**Comment by lclarkg18** [comment]
:(

**Comment by lclarkg18** [comment]
Merge first

**Comment by kieranw-8** [comment]
@lclarkg18 I have slightly changed your constraint implementation. Firstly the checks are no longer duplicated in save(), and secondly your Q expression was not functioning as expected so the constraint has been translated to a conditional in full_clean()

**Comment by lclarkg18** [comment]
Why isn't the CheckConstraint working? It was working well for me. Putting it in full_clean is okay but using Django constraints is better practice.

**Comment by lclarkg18** [comment]
Good on the save though

**Comment by lclarkg18** [comment]
I'm only overriding full_clean cause I couldn't figure out an implementation for it with constraints

**Comment by kieranw-8** [comment]
The test for checking simultaneous ownership and officership was failing. It only passed before as the full_clean implementation of checking for a single owner was always failing if any single owner existed, as the check did not exclude itself.

**Comment by lclarkg18** [comment]
Disappointing, thanks for catching!

**Pull request merged**
