### PR TITLE
033.1 test withdraw from tournament

### PR DESCRIPTION
**Pull request by ukanishk**

### CODE REVIEW

**Comment by lclarkg18** [comment]
Looks good, just a couple things:
1. Success and error messages should be raised in each case
2. Redirect should probably be to show club, not show clubs.
3. A doubt, when you write get member in the form, is that checking that the member exists? get isn't safe in the sense that it will raise an exception if there isn't a member with that user and club so is that accounted for?

**Comment by ukanishk** [comment]
The first two points are fine but I do not understand the third one. Where do you see a form? It is safe as we are not deleting a member but a participant and I am already checking for its existence.

**Comment by kieranw-8** [comment]
You don't consider the case that line 87 throws a non-existence error, i.e. the user making the request is not a member of the club.

**Comment by lclarkg18** [comment]
Exactly, and the same for line 50 (although I am aware that is old code), don't you have to filter+exists first?

**Comment by lclarkg18** [comment]
Also, question for anyone, isn't deadline > now() checking you're withdrawing after the deadline?

**Comment by kieranw-8** [comment]
@lclarkg18 deadline > now <-> the deadline takes place after 'now'

**Comment by lclarkg18** [comment]
> @lclarkg18 deadline > now <-> the deadline takes place after 'now'

Thanks! definitely me being picky but I feel like now < deadline is more readable.

**Comment by kieranw-8** [comment]
🤦

**Comment by kieranw-8** [comment]
Looks good but will merge locally tomorrow to ensure no conflicts (tests wont run automatically)

**Pull request merged**
