### PR TITLE
X025 officer and owner organise tournament

### PR DESCRIPTION
**Pull request by michaelmulianto**
- restrict access for non owner and non officer to organise tournaments
- added test cases
- fix join tournament test case

### CODE REVIEW

**Comment by lclarkg18** [comment]
1000 lines? Something is wrong with version control, merge locally first

**Comment by lclarkg18** [comment]
For example join tournament view was already tested for

**Comment by kieranw-8** [comment]
Join tournament view is already working so not sure what you've done here... also you appear to be overwriting a lot of random test files for no reason

**Comment by michaelmulianto** [comment]
> For example join tournament view was already tested for

Join tournament had a fail test so had to fix the fixtures

**Comment by kieranw-8** [comment]
This is going to break too much to merge, please make a new branch and copy the relevant code over, and submit a pull request on this new branch.

**Pull request closed without merging**
