### PR TITLE
X022 add error page view tests

### PR DESCRIPTION
**Pull request by JohnKellyTamargo**

### CODE REVIEW

**Comment by lclarkg18** [comment]
This should have probably gone to main but since it's coded on a branch checkout from epic3 main then we have to options:
1. Reject this, copy paste the code into a new branch checkout from main
2. A slightly dirtier, accept and move on, merge into epic3.

I think it's best we go with 1, I know it's more work and it's now looking very likely we will finish epic 3 but still we want to have two complete versions of the system running.
If you do this, please use the same branch name. You can achieve this by doing the tasks in the following order:
1. delete the branch locally by git branch -D {branch name}
2. copy pasta the code from the remote (from GitHub) into a new branch (checkout from main)
3. delete the remote on GitHub or with git branch -d {branch name}
4. push the local branch to remote and pull request again to main

**Comment by lclarkg18** [comment]
The work itself looks really solid! 10/10!

**Comment by kieranw-8** [comment]
fixes #115

**Comment by kieranw-8** [comment]
Will leave for now... personally I am confident we can complete epic 3 so merge not too much of an issue, but I agree 1 is safer

**Pull request merged**
